services:
  backend:
    build: .
    container_name: backend
    volumes:
      - ./images:/app/images
      - ./logs:/app/logs
    expose:
      - 8000
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html/static:ro
      - ./images:/usr/share/nginx/html/images:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge